artifact_location: /Users/rudy.enero/PycharmProjects/MLflowProject/artifacts_exp
creation_time: 1711057122340
experiment_id: '718496535188259967'
last_update_time: 1711057122340
lifecycle_stage: active
name: create_exp
